### ISSUE TITLE
GUI conflict, unable to load bitcoin-qt

### ISSUE THREAD

**Issue by jorishr** [BenWestgate/bitcoin-core-on-tails#6]
- Describe the issue
Tails OS 5.8
When clicking on the bitcoin core icon in the menu, nothing happens.
When loading the bitcoin-qt binary from the terminal I get an error message (see screenshot below).

![Screenshot from 2023-01-15 19-35-37](https://user-images.githubusercontent.com/45603244/212634376-e671f470-7708-4198-942c-00d3a0e69b4f.png)

- Possible fix
When changing the environment variable manually via the terminal before each run, the issue is resolved. Bitcoin core gui is loaded and the application works as expected. Although, a warning persists in the terminal window (see screenshot).

- Questions
Unsure if this issue is related to Tail OS, Bitcoin Core or this repo.

What config files do I need to edit to that make my fix permanent?

**Comment by BenWestgate** [comment]
This is a known issue in Tails 5.8 with all Qt apps.
https://gitlab.tails.boum.org/tails/tails/-/issues/19326

to make the fix permanent, you should turn on dotfiles in the Persistent Storage application, then enter the following commands in terminal

`echo 'export QT_QPA_PLATFORM="wayland;xcb"' | tee -a $HOME/.bashrc`
followed by
`cp $HOME/.bashrc /live/persistence/TailsData_unlocked/dotfiles/.bashrc`

I just had to write this automation for the sister project https://github.com/BenWestgate/Bails
